### ISSUE TITLE
Move playbooks from https://gitlab.cee.redhat.com/snowdrop/devops/tree/master/ocp-deploy

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/openshift-infra#27]
We still have internal playbooks that we could integrate here as they aren't specific to the Red Hat infrastructure and could be used to create/delete openstack VM, ....

Playbooks : 
- create_vm.yml (used to create/delete a vm on openstack)
- keys.yml could be used as a generic way to create private/public and import it within the vm ....
- config_dns could also become part of this project

**Comment by geoand** [comment]
Actually `config_dns` is very Red Hat specific, since it assumes 
* a specific IP address for the DNS server
* a username and key used to login to the DNS server
* The DNS server is specifically a BIND DNS server, that is running as a systemd Service.

The `create_vm` playbook is not specific, but I don't think it makes sense to add it here, since it just calls the Ansible Openstack modules without doing much else.

**Comment by cmoulliard** [comment]
> since it just calls the Ansible Openstack modules without doing much else.

Nevertheless, we have customize it to be able to create/delete a VM on openstack, inject keys. Such work should be recuperated and merged here.

**Comment by cmoulliard** [comment]
> Red Hat specific

Excepted this entry `dns_conf_file: "{{user_name}}.osepool.centralci.eng.rdu2.redhat.com.conf"`, the rest of the main.yml is not Red Hat specific ....

**Comment by geoand** [comment]
As I mentioned above, the other points are also specific to the setup we use internally.
